### ISSUE TITLE
this.formValidation is undefined

### ISSUE THREAD

**Issue by sijad** [Lemoncode/fonk-formik#12]
this error shows up when `formValidation.validateForm` passed to `validation` directly:

```
  const formik = useFormik<FormValues>({
    initialValues: values,
    validate: formValidation.validateForm,
    onSubmit,
  });
```

solution 1:

```
  function validate(values: FormValues) {
    return formValidation.validateForm(values);
  }
  const formik = useFormik<FormValues>({
    initialValues: values,
    validate,
    onSubmit,
  });
```

solution 2:

please considering using es6 arrow function for public methods too
or bind them in `fonk-formik` `constructor` method.

**Comment by brauliodiez** [comment]
Thanks a lot @sijad for reporting this, ... it's a basic detail we have missed (still bind this hurts in classes :)), we will do that and release a minor version soon @Nasdan

**Comment by Nasdan** [comment]
Hi @sijad, we just released [v.4.0.1](https://github.com/Lemoncode/fonk-formik/releases/tag/v4.0.1)
Thank you for reporting the issue.

**Comment by sijad** [comment]
fixed, Thanks!
