### ISSUE TITLE
formik compatible errors object

### ISSUE THREAD

**Issue by sijad** [Lemoncode/fonk-formik#9]
fonk-formik error is not compatible with formik errors.

for example:

```js
const validationSchema = {
  field: {
    'translations.0.title': [Validators.required.validator],
  },
};

const formValidation = createFormikValidation(validationSchema);

const formik = useFormik<FormValues>({
  initialValues,
  onSubmit,
  validate: values => formValidation.validateForm(values),
});

console.log(formik.errors);
```

currently produced errors object looks like this:

```json
{
  "translations.0.title": "Please fill in this mandatory field.",
  "recordErrors": {}
}
```

but it should look like this:

```json
{
  translations: [
    { title: "Please fill in this mandatory field."}
  ],
}
```

this will allow get field error using `useField` for example:

```js
const [field, meta] = useField(name);
console.log(meta.error);
```

**Comment by brauliodiez** [comment]
Thanks for reporting, coul you confirm this affect only to nested fields? We will dig into that case

**Comment by sijad** [comment]
it does affect both nested and array fields.

please checkout this example: https://codesandbox.io/s/validate-field-w76hf

also please note formik will consider none empty errors object as not validate form (and prevent submitting the form), therefore formkik will also consider `recordErrors` as an field error too.

**Comment by sijad** [comment]
as a workaround you can use `lodash.set` to convert fonk error to formik error:

```js
import set from 'lodash.set';
// ...
const formik = useFormik<FormValues>({
  initialValues: values,
  validate: async values => {
    const fonkErrors = await formValidation.validateForm(values);
    const errors: { [x: string]: string } = {};

    if (fonkErrors) {
      Object.keys(fonkErrors).forEach(k => {
        set(errors, k, fonkErrors[k as keyof typeof fonkErrors]);
      });
    }

    return errors;
  },
  onSubmit,
});
// ...
```

**Comment by brauliodiez** [comment]
Totally agree I was thinking about that solution, using lodash.set for the nested fields but would that work for the array validations?

**Comment by sijad** [comment]
it works for static array indexes fields:

```js
const validationSchema = {
  field: {
    'translations[0].title': [Validators.required.validator],
  },
};
```

but I'm not sure how it can be applied for all of array indexes

**Comment by brauliodiez** [comment]
I will break it into two issues: 
- Error reporting: Provide support for nested fields (I think this can be straight forward),.
- Error reporting: Provide support for array validations

**Comment by sijad** [comment]
I think validating nested array is related to fonk itself.
currently there's no way (?) to validating all array indexes fields e.g.:

```
const validationSchema = {
  field: {
    'translations.*.title': [Validators.required.validator],
    'translations.*.hint': [Validators.required.validator],
  },
};
```

should I open an issue in fonk for this?

**Comment by brauliodiez** [comment]
Yes please, I think it will need further investigation, the approach you are mentioning sounds quite interesting, when it find that special characters it would know that the field is an array and traverse over all the elements.

**Comment by brauliodiez** [comment]
Closing this issue, splitted into two:

- [fonk formik]Handling nested fields #10
- [fonk]Validating nested array fields: https://github.com/Lemoncode/fonk/issues/92
